FROM python:3.10

WORKDIR /app

# Install compilation toolchain
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY dataset_generator.py train.py app.py ./

# Generate dataset and train the model binary during docker build
RUN python dataset_generator.py && python train.py

EXPOSE 8000

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]