services:
  cache:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spam-api-compose
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - CACHE_TTL=3600
      - MODEL_PATH=model.joblib
    depends_on:
      - cache
    restart: always